version: '3.5' 
services: 
    mariadb:
        container_name: mariadb
        image: 'mariadb:10.4'
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=database
        restart: 'always'
        volumes:
        - mariadb:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        ports: 
            - 8080:80
        links:
            - mariadb:db
    php:
        container_name: laravel
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            # I map this to 443 on my host so I don't need to specify it
            - 80:80
        depends_on:
            - mariadb
        volumes:
            - ./:/var/www/html
            - ./dockerfiles/local.conf:/etc/apache2/sites-available/000-default.conf
volumes:
    mariadb: